name: Main Pipeline

on:
    push:
        branches:
            - main

jobs:
    build-test:
        uses: ./.github/workflows/reusable-build-test.yml
        with:
            python_version: "3.11"
            run_tests: true

    docker:
        needs: build-test
        uses: ./.github/workflows/reusable-docker.yml
        with:
            image_name: gha-capstone
            tag: latest
            docker_username: ${{ vars.DOCKER_USERNAME }}
        secrets:
            docker_password: ${{ secrets.DOCKER_PASSWORD }}

    docker-sha:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Build SHA Tag
              run: |
                SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
                echo "Tag = sha-$SHORT_SHA"
    
    security-scan:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - uses: aquasecurity/trivy-action@master
              with:
                image-ref: ${{ needs.docker.outputs.image_url }}
                format: sarif
                output: trivy-results.sarif
                
            - uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: trivy-results.sarif

    deploy:
        needs: security-scan
        runs-on: ubuntu-latest
        environment: 
            name: production
        steps:
            - run: |
                 echo "Deploying image:"
                 echo "${{ needs.docker.outputs.image_url }}"
            





